rpc:
	sudo /etc/init.d/binary_rpc_redis_general restart
ws:
	sudo /etc/init.d/binary_websocket_api restart
pd:
	sudo /etc/init.d/binary_pricer_daemon restart
pq:
	sudo /etc/init.d/binary_pricer_queue restart
exd:
	sudo /etc/init.d/binary_expiryd restart
bo:
	sudo /etc/init.d/binary_starman_bom-backoffice restart

rpc_stop:
	sudo /etc/init.d/binary_rpc_redis_general stop
ws_stop:
	sudo /etc/init.d/binary_websocket_api stop
pd_stop:
	sudo /etc/init.d/binary_pricer_daemon stop
pq_stop:
	sudo /etc/init.d/binary_pricer_queue stop
exd_stop:
	sudo /etc/init.d/binary_expiryd stop
bo_stop:
	sudo /etc/init.d/binary_starman_bom-backoffice stop

rpc_start:
	sudo /etc/init.d/binary_rpc_redis_general start
ws_start:
	sudo /etc/init.d/binary_websocket_api start
pd_start:
	sudo /etc/init.d/binary_pricer_daemon start
pq_start:
	sudo /etc/init.d/binary_pricer_queue start
exd_start:
	sudo /etc/init.d/binary_expiryd start
bo_start:
	sudo /etc/init.d/binary_starman_bom-backoffice start
