rpc:
	sudo /etc/init.d/binary_rpc restart

ws:
	sudo /etc/init.d/binary_websocket_api restart

pd:
	sudo /etc/init.d/binary_pricer_daemon restart

rpcp:
	sudo /etc/init.d/binary_pricer_daemon restart
	sudo /etc/init.d/binary_rpc restart

bo:
	sudo /etc/init.d/binary_starman_bom-backoffice restart
